### ISSUE TITLE
Heroku shiny app greys out after about a minute

### ISSUE THREAD

**Issue by mauritzvdworm** [virtualstaticvoid/heroku-shiny-app#1]
App greys out after about a minute of no use.

The code below was suggest [here](https://stackoverflow.com/questions/54594781/how-to-prevent-a-shiny-app-from-being-grayed-out/54604662#54604662) 

`autoInvalidate <- reactiveTimer(10000)
  observe({
    autoInvalidate()
    cat(".")
  })`

I have tried it and it does not solve the issue.

**Comment by virtualstaticvoid** [comment]
Hi @mauritzvdworm 

This issue has come up before and has to do with an [inactivity timeout](https://devcenter.heroku.com/articles/request-timeout#long-polling-and-streaming-responses) on Shiny's websocket connection to Heroku. You can check the application logs to confirm this.

The solution described [here](https://github.com/rstudio/shiny/issues/2110#issuecomment-419971302) has worked for me in the past. 

Shiny documentation has a article on [Reconnecting to Shiny apps](https://shiny.rstudio.com/articles/reconnecting.html) which may help, although I haven't tried this.

See also https://github.com/virtualstaticvoid/heroku-buildpack-r/issues/97 and https://github.com/virtualstaticvoid/heroku-buildpack-r/issues/126 for discussions the issue.

HTH

**Comment by mauritzvdworm** [comment]
The link to the solution seems to be a decent workaround, thanks.
